import { Div, Text } from "@components";
import styles from "./index.module.css";
import { SPLASH_SIMILAR_WORDS } from "@constants";
import { useStoreHydration } from "@store";
import { Outlet } from "react-router-dom";

const Layout = () => {
  const isHydrated = useStoreHydration();

  if (isHydrated) {
    return (
      <main>
        <Div className={styles.wrapper}>
          <Outlet />
        </Div>
      </main>
    );
  }

  return (
    <Div className={styles.container}>
      <Div className={styles.containerContent}>
        <Div className={styles.header}>
          <Div className={styles.logoWrapper}>
            <img
              src={require("@assets/images/icons/logo.png")}
              className={styles.logo}
              alt="logo"
            />
          </Div>
          <Div>
            <Text as="h1" className={styles.title}>
              aura
            </Text>
            <Text as="p" className={styles.subtitle}>
              /ˈɔːrə/
            </Text>
          </Div>
        </Div>

        <Text as="p" className={styles.definition}>
          noun: <strong>aura</strong>; plural noun: <strong>aurae</strong>;
          plural noun: <strong>auras</strong>
        </Text>

        <Div>
          <Text as="p" className={styles.definition}>
            the distinctive atmosphere or quality that seems to surround and be
            generated by a person, thing, or place.
          </Text>
          <Text as="p" className={styles.example}>
            "the ceremony retains an aura of mystery"
          </Text>

          <Div className={styles.tagContainer}>
            {SPLASH_SIMILAR_WORDS.map((word, index) => (
              <Div key={index} className={styles.tag}>
                <Text as="span" className={styles.tagText}>
                  {word}
                </Text>
              </Div>
            ))}
          </Div>
        </Div>
      </Div>
    </Div>
  );
};

export default Layout;
