import logoImage from '@assets/images/icons/logo.png';
import {Div, Text} from '@components';
import {SPLASH_SIMILAR_WORDS} from '@constants';
import styles from './Dictionary.module.css';

export const Dictionary: React.FC = () => (
  <Div className={styles.container}>
    <Div className={styles.content}>
      <header className={styles.header}>
        <Div className={styles.logoWrapper}>
          <img src={logoImage} className={styles.logo} alt="Aura Logo" width={40} height={40} />
        </Div>
        <Div>
          <Text as="h1" className={styles.title}>
            aura
          </Text>
          <Text as="p" className={styles.subtitle}>
            /ˈɔːrə/
          </Text>
        </Div>
      </header>

      <section className={styles.definitionSection}>
        <Text as="p" className={styles.definition}>
          noun: <strong>aura</strong>; plural noun: <strong>aurae</strong>; plural noun:{' '}
          <strong>auras</strong>
        </Text>

        <Text as="p" className={styles.definition}>
          the distinctive atmosphere or quality that seems to surround and be generated by a person,
          thing, or place.
        </Text>

        <Text as="p" className={styles.example} role="note">
          "the ceremony retains an aura of mystery"
        </Text>

        <Div className={styles.tagContainer} role="list">
          {SPLASH_SIMILAR_WORDS.map((word) => (
            <Div key={word} className={styles.tag} role="listitem">
              <Text as="span" className={styles.tagText}>
                {word}
              </Text>
            </Div>
          ))}
        </Div>
      </section>
    </Div>
  </Div>
);
